Title = "Buffalo Editing"
baseURL = "https://tomanistor.com"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Buffalo Editing"
    author = "Toma Nistor"
    description = "Buffalo Editing is an editing and proofreading service based in Philadelphia, PA."
    logoBig = "/images/buffalo.jpg"
    logoSmall = "/images/buffalo.jpg"
    favicon = "favicon.ico"
    opengraphImage = "/images/osprey.png"
    linkedin = "tomanistor"
    github = "tomanistor"
    email = "angel@buffaloediting.com"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Services"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
